### ISSUE TITLE
Compatible with WP Fastest Cache

### ISSUE THREAD

**Issue by melleman** [kamalkhan/kk-star-ratings#1]
It will be nice, when KK Star rating will be compatible with WP Fastest Cache. You can vote multiple if the page with WP Fastest Cache will cache and you reload the page after a vote.

**Comment by kamalkhan** [comment]
Never used wp fastest cache. You may send a PR.

**Comment by mediamarx** [comment]
I'm (and many others are, too,) interested in a solution:
https://wordpress.org/support/topic/incompatibilidad-de-kk-satar-ratings-con-plugin-wp-fastest-cache/
Seems also not to work with WP Super Cache:
https://wordpress.org/support/topic/wp-super-cache-kk-star-rating/

Are there caching plugins kk star ratings is working with?
