### ISSUE TITLE
bhittani_plugin_kksr_js is not defined

### ISSUE THREAD

**Issue by worldelse** [kamalkhan/kk-star-ratings#10]
Hello,

I have an error in my console with this plugin ! I really loved to use it but with this error my page is not displaying.
The error is : Uncaught ReferenceError : bhittani_plugin_kksr_js is not defined

Could you help ?

Thank you

**Comment by leecollings** [comment]
Are you referencing the correct files? Is jQuery loading okay? Are there any other errors?

**Comment by worldelse** [comment]
Yes JQuery loading is ok :) this is the only error :)

Thanks for your help !

**Comment by kamalkhan** [comment]
Please read Issue #18
