### ISSUE TITLE
How can I remove / erase or reset intentional Reviews !

### ISSUE THREAD

**Issue by kabirbd89** [kamalkhan/kk-star-ratings#103]
I am thinking about implementing this plugin in a wide multi user community blog. Where there is a chance to misusage the guest review option. 
Intentionally any visitor or group of visitor may use this option. In that cases how can I reset or remove rating data from that specific post/s or page/s.

**Comment by Yerrun** [comment]
What I do is going to the database and look for the star rating table. I can remove the ratings there. When I want to remove it from my page I go to edit the post, then to the custom fields and then adjust the rating manually. I don't see an other way of doing it.
