### ISSUE TITLE
You latest update has critical error

### ISSUE THREAD

**Issue by cmdntd** [kamalkhan/kk-star-ratings#113]
This make many problems when this make my web a notice critical error

![1b57528df7983fc66689](https://user-images.githubusercontent.com/1112881/139618922-89887ffb-c88d-46e6-aa39-23eb951aa689.jpg)

**Comment by esmaeil98** [comment]
My site was very slow after the update and I wanted to disable the plugin, it gave a connection error to the database. please check

**Comment by perleatspython** [comment]
Hello,
first of all, many thanks for the PlugIn.

I probably have the same problems as the previous speakers. After the update, the migration process stops in an endless loop. I have not yet had the chance to run an SQL monitor, but it looks like numerous queries are being executed. The scripts run until the set timeout time and slow down the server extremely.
I have currently deactivated the plug-in. If there is anything you want me to investigate, please let me know. Offtopic: Which DB entry marks the migration process? So I could check the behaviour of the plug-in with supposedly performed migration process.

Best regards

**Comment by kamalkhan** [comment]
Remove version 5.1.x in favour of 5.2.0 which should mitigate the issue.

**Comment by perleatspython** [comment]
Hello Kamal,
the fix seems to solve the Problem. At least for me.
Good work and thanks for the quick fix.
Best regards ...
