### ISSUE TITLE
How to change the Language?

### ISSUE THREAD

**Issue by graphicsarea** [kamalkhan/kk-star-ratings#120]
I Uploaded kk-star-ratings-tr_TR.mo to change the language of the plugin to the Turkish Language, But it's not work!

Please Help.

**Comment by kamalkhan** [comment]
I'll take a loot at this issue.

**Comment by kamalkhan** [comment]
Okay thanks.

**Comment by graphicsarea** [comment]
> Okay thanks.

You're Welcome, Waiting for your reply <3

**Comment by graphicsarea** [comment]
Any updates?

**Comment by kamalkhan** [comment]
This has been fixed in 5.2.10

**Comment by graphicsarea** [comment]
I'm asked any update for this issue not the plugin version!
