### ISSUE TITLE
action "kksr_rate" no longer exists?

### ISSUE THREAD

**Issue by flyonthenet** [kamalkhan/kk-star-ratings#121]
Seems that action "kksr_rate" isn't longer invoked by version 5 of this plugin: I've searched for it in the code but I didn't find it.
Some plugins are still using it, like WP Fastest Cache to clear page cache after voting.
(version 1.0.2, file wpFastestCache.php, line 151)

This action has been replaced with another one?
Could be restored to maintain backward compatibility?

Thanks in advance
D.

**Comment by kamalkhan** [comment]
Thanks for letting me know. Will be available in next release.

**Comment by flyonthenet** [comment]
I've tested version 5.3.1 and now it's fine

Thanks
D.
