### ISSUE TITLE
fatal error after site transfer to another domain

### ISSUE THREAD

**Issue by jerri69** [kamalkhan/kk-star-ratings#126]
After moving page from development domain to live kkstar not working - fatal error issued

## Detailed description

Fatal error: Uncaught Error: Attempt to assign property "plugins" on bool in /home/suknie/domains/example.pl/public_html/wp-content/plugins/kk-star-ratings/freemius/start.php:74 Stack trace: #0 /home/suknie/domains/example.pl/public_html/wp-content/plugins/kk-star-ratings/freemius.php(15): require_once() #1 /home/suknie/domains/example.pl/public_html/wp-content/plugins/kk-star-ratings/freemius.php(35): kksr_freemius() #2 /home/suknie/domains/example.pl/public_html/wp-content/plugins/kk-star-ratings/index.php(32): require_once('/home/suknie/do...') #3 /home/suknie/domains/example.pl/public_html/wp-admin/includes/plugin.php(2314): include_once('/home/suknie/do...') #4 /home/suknie/domains/example.pl/public_html/wp-admin/plugins.php(192): plugin_sandbox_scrape('kk-star-ratings...') #5 {main} thrown in /home/suknie/domains/example.pl/public_html/wp-content/plugins/kk-star-ratings/freemius/start.php on line 74

## Your environment

* Version used (e.g. PHP 8.1,):
* Link to your project:
* ...
* ...

**Comment by kamalkhan** [comment]
These errors seem to be propagating from the freemius sdk. The sdk has been updated to the latest version (2.5.1) in the latest version of the plugin (5.4.1). Hopefully this fixes these errors.
