### ISSUE TITLE
Query monitor and Php Xray - ERRORS

### ISSUE THREAD

**Issue by JhonDoex** [kamalkhan/kk-star-ratings#127]
I have installed Query monitor and i got this error i scanned on the cpanel with PHP Xray
and i got there errors and the plugin is loading very slow.
## Detailed description

![image](https://user-images.githubusercontent.com/118278694/201930274-95aa350d-d6f3-4256-984d-064dfaa67985.png)

Tested with PHPXray
![WhatsApp Image 2022-11-15 at 03 09 12 (1) (1)](https://user-images.githubusercontent.com/118278694/201931926-527043ae-238f-4452-b2b4-7a24d6e419e6.jpeg)

## Possible implementation

Please in next update can you solve this errors, thank you for your contribution to this plugin is the best i tested a lot o plugins but they are not working and they are with money so yours is free but working.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used (e.g. PHP 8.1):

**Comment by kamalkhan** [comment]
Most of those errors are coming from the integration of freemius. I will try to include an updated version of the freemius api code in the next release.
