### ISSUE TITLE
Stars doesn't appear in desktop nor mobile version

### ISSUE THREAD

**Issue by VoyageursGourmands** [kamalkhan/kk-star-ratings#131]
##
The Stars doesn't appear in desktop nor mobile version. I have download the plugin yesterday, and when i am connected on wordpress, i can see the stars (with or without notes).
But when unlogged, it doesn't appeard. I have tried in other computers, asked people to check on theirs or on mobiles, same.

This is a page without any review : https://voyageursgourmands.fr/journee-a-lisbonne/
This is a page with review : https://voyageursgourmands.fr/visiter-dinant-weekend/

PHP 8.0
WordPress 6.1.1
Theme : Simple Mag

Thanks in advance for your help

**Comment by kamalkhan** [comment]
I see the star ratings on both pages as guest (not logged in).
