### ISSUE TITLE
Not show stars rating in search result

### ISSUE THREAD

**Issue by edwinston** [kamalkhan/kk-star-ratings#15]
It has been 3 weeks since I set rating for my article, already enabled Google Rich Snippets in setting but it doesn't show stars rating in search result.

**Comment by kamalkhan** [comment]
Please read Issue #18

**Comment by kamalkhan** [comment]
@sweetclues You will have to depend on google for your ratings to show up in google search results. I don't think it has anything to do with the code as it does work for most of the people.

**Comment by kamil-HFC** [comment]
@edwinston You have stars in google results, but I still haven't. How did you resolve this issue?

**Comment by edwinston** [comment]
kk-rating works fine on some post on my site, some are not. So I use a
different plugin instead

2017-12-11 19:13 GMT+07:00 kamil-HFC <notifications@github.com>:
