### ISSUE TITLE
KK-Star-Ratings Listify WP Job Manager Custom Post Type

### ISSUE THREAD

**Issue by premierpools** [kamalkhan/kk-star-ratings#26]
Kamal:

I've been using this plugin for a while now on a bunch of sites. It works awesome. Never had a problem deploying it before until I tried to integrate it with a custom post type. I'm trying to substitute your rating system in Listify and figured out how to add the rating code to my template but can't get it to show up because it's a custom post type. How do I get it to recognize job_listing from WP Job Manager?

**Comment by tanazmusic** [comment]
the information is best 
[دانلود آهنگ](http://tanazmusic.ir)
[طناز موزیک](http://tanazmusic.ir/)
