### ISSUE TITLE
Error in Failure Console

### ISSUE THREAD

**Issue by melleman** [kamalkhan/kk-star-ratings#3]
When i go to my homepage and use the failure console, this JS failure is shown.

TypeError: k[l] is undefined
c.fn.kkstarratings.fetch/<.success/<()
.each()
c.fn.kkstarratings.fetch/<.success()
m.Callbacks/j()
m.Callbacks/k.fireWith()
x()
.send/b()

**Comment by kamalkhan** [comment]
Please read Issue #18
