### ISSUE TITLE
Problems to save changes !!

### ISSUE THREAD

**Issue by MaurodaSilva** [kamalkhan/kk-star-ratings#30]
Hello!

I'm having trouble saving some changes to the plugin settings, for example I tried to activate the "Unique Based On User IP" option, I click save but it does not save the settings, not even for any other option I'm getting.

can anybody help me?

Thank you!

**Comment by ghonchesefidi** [comment]
Hi
Send me an access of your admin panel i will check ot for u

**Comment by Budget101** [comment]
same, it "saves" but then goes right back to the previous settings, cannot change the location, the IP settings, any of them, the save is only temporary.
