### ISSUE TITLE
Change color for "Thank You"

### ISSUE THREAD

**Issue by mlustig71** [kamalkhan/kk-star-ratings#35]
Hi,
I can't find the css-style for thankyou. I don't want the green. 
It is too fast for firebug and it is not in the css.css.

Can You tell me the css-class?

Thank You,
Marion

**Comment by ghonchesefidi** [comment]
you should change this class:
`	Line 45: 					color : "green"
	Line 157: 						$('.kksr-legend', obj).html('<span style="color: green">'+$.fn.kkstarratings.options.thankyou+'</span>');
`
on this file:
kk-star-ratings\js.js
