### ISSUE TITLE
Image links not updated after domain changed

### ISSUE THREAD

**Issue by and7ey** [kamalkhan/kk-star-ratings#37]
I've started to host my Wordpress instance on another IP address, but Kk star images are still taken from another domain (and it doesn't work):

Here is the CSS used per Chrome Dev Tools:
```
(index):49
.kk-star-ratings .kksr-star.gray {
    background-image: url(http://MY.OLD.IP.ADDRESS/wp-content/plugins/kk-star-ratings/gray.png);
}
```

The following code is not used:
```
css.css?ver=2.5.1:24
.kk-star-ratings .kksr-star.gray {
    background-image: url(gray.png);
}
```

and I don't understand how to fix it. Tried to delete plugin and install again - doesn't help.

**Comment by kamalkhan** [comment]
Try deleting the images and uploading them again using the images section of the plugin settings.

**Comment by and7ey** [comment]
I am new to Wordpress. Could you please clarify how to delete them? And where to take images now to upload them again?

**Comment by kamalkhan** [comment]
You can modify the images in the settings of the plugin. See the below screenshot. Delete the 3 images from the page by clicking on the cross icons and upload them individually by locating to the plugin folder on your local machine or somewhere and choosing the correct images.

![screenshot](https://ps.w.org/kk-star-ratings/trunk/screenshot-2.png?rev=1678791)

**Comment by and7ey** [comment]
Thanks. I found images at http://mynewaddress.com/wp-content/plugins/kk-star-ratings/yellow.png, but I was having some problems with updating gray star (yellow and orange was updated successfully), so I've just deleted all images and pressed Save - it fixed the problem.

Thanks for your prompt help!

**Comment by kamalkhan** [comment]
Yes you can also delete the images and it should load the default images.
