### ISSUE TITLE
[avg] ([per]) [total] voto[i]

### ISSUE THREAD

**Issue by MosaikoWeb** [kamalkhan/kk-star-ratings#4]
In my website, after last update, the result appears as this: [avg]([per]) [total] voto[i]
Check it on http://www.newyorkfacile.it/alloggi/hotel/, as on every page on this website.

Thank you

**Comment by kamalkhan** [comment]
Try clearing your cache. https://wordpress.org/support/topic/avg-per-total-votes

**Comment by MosaikoWeb** [comment]
Cleared cache many times (wp total cache) but nothing changed.
The only way is :

    1- Disable new version (not delete)
    2- Rename the plugin folder to something else, like add "-new" at the end
    3- Install 2.4.1 and activate

or are there any alternatives?
Thnakyou

**Comment by kamalkhan** [comment]
I will have a look at it.

**Comment by MosaikoWeb** [comment]
Reverted back until plugin will be fixed.
I have another issue: plugin works regular on mozilla firefox, but not work on chrome and safari.
Stars appears all grey, and seems that js not work. In each page. 

Is a known issue? Have you any suggestions? 
(both versions 2.4.1. and 2.5.1)

Thanks for supporting

**Comment by kamalkhan** [comment]
Strange, the values are showing up correctly for me. I can not replicate the bug so I don't know what to do here. It also works on chrome and safari for me.

**Comment by Angristan** [comment]
Same bug here, I'm using WP-Rocket.
![screenshot_26-07-2016_qndpakzp](https://cloud.githubusercontent.com/assets/11699655/17145877/720b9df2-535c-11e6-8c5a-45cece08e6f2.png)

Any solution ?

**Comment by charles1888** [comment]
After update kk star ratings from v2.4.1 to v2.5.1 when I rate a post, the plugin don't show the stats in the legend, instead show [avg] ([per]) [total] vote[s].
Also when I focus the stars the "undefined" word appear below. I tested kk star ratings v2.4.1 and works fine. Please note that I am using WordPress 4.5.3. Thanks!

**Comment by monecchi** [comment]
Same happens using kk star ratings on WordPress 4.6.1, before updating WordPress the plugin was working fine.

**Comment by zkvvoob** [comment]
Just want to say that I'm having the same problem. Went back to 2.4.1 and waiting for the bug to be fixed.

**Comment by rohitink** [comment]
The Real solution to this problem is to change the value of that field. [avg] ([per]) [total] vote[s]

Change it to anything like `Average Rating: [avg] from [total] total vote[s]`

**Comment by zkvvoob** [comment]
@rohitink Thanks a lot for this, mate. I can confirm it's working now.

**Comment by rohitink** [comment]
You're Welcome :)

**Comment by monecchi** [comment]
Hi there. I hope all of you are doing well!

Although this is a great plugin, I haven't seem any new features and updates in a very long time. So I thought it'd be a valid point to invite the plugin users who are comfortable with programming to come up with a few enhancements and updates.

Anyone interested on helping to enhance this plugin?

While using the plugin I've managed to:

- Completely redesign the settings page with a new UI, making it responsive and a bit more elegant. 
- Internationalized the whole plugin allowing translations.
- Added "Display on Post Types" option, to allow the star ratings to be displayed under custom post types.
- Added new "Custom Position" option so users are free to set a position with their own custom css.

This is a work in progress, HOWEVER,
As I'm not a developer, I'm missing the skills to build the functions as they should be... I've created the functions, and although they're working, I'm sure they're totally messed by my lack of knowledge.

Todo list:

- Create the function that gets all the custom post types and returns an array of options.

- Create a new form element "multiple select" field under `markup.class.php` to grab the options from the "get post types" function.

-  Create a kind of `is_post_type()` function to check against the array of selected post types, so we can filter for which custom post types to display the star ratings when the option "Display on Post Types" is enabled.

For anyone interested on trying and improving my version of the KK Start Ratings, please go on and mess around with the plugin files under the following repository: https://github.com/monecchi/KK-Star-Ratings-New-UI.git

Sorry for the gif quality, it doesn't really show how great the new UI looks like.

![kksr-animated](https://cloud.githubusercontent.com/assets/5252519/20775258/29703956-b741-11e6-9db8-4a2088721c74.gif)

**Comment by kamalkhan** [comment]
Please read Issue #18

**Comment by tanazmusic** [comment]
**[طناز موزیک](http://tanazmusic.ir)**

> [دانلود آهنگ جدید](http://tanazmusic.ir/)

سریال عاشقانه یک سریال محبوب و جدید نزد ایرانیان است.این سریال هم اکنون در فروشگاه های فروش فیلم ایرانی به فروش میرسد.[دانلود سریال عاشقانه](http://tanazmusic.ir/%d8%af%d8%a7%d9%86%d9%84%d9%88%d8%af-%d8%b3%d8%b1%db%8c%d8%a7%d9%84-%d8%b9%d8%a7%d8%b4%d9%82%d8%a7%d9%86%d9%87-%d8%aa%d9%85%d8%a7%d9%85-%d9%82%d8%b3%d9%85%d8%aa-%d9%87%d8%a7/) با لینک مستقیم از طناز موزیک امکان پذیر است.
[دانلود آهنگ جدید ماکان باند بنام هر بار این درو](http://tanazmusic.ir/%d9%85%d8%a7%da%a9%d8%a7%d9%86-%d8%a8%d8%a7%d9%86%d8%af-%d9%87%d8%b1-%d8%a8%d8%a7%d8%b1-%d8%a7%db%8c%d9%86-%d8%af%d8%b1%d9%88/)
