### ISSUE TITLE
Multiple Unique ratings on single page

### ISSUE THREAD

**Issue by jcass1** [kamalkhan/kk-star-ratings#41]
Hi, 

I have several comparison tables on my site, used to compare products. 
I want to use the rating shortcode to allow users to submit votes on each product. 

The problem is that if you vote on one product, it applies the same vote to all other products. 

Is there a way to allow for multiple, unique votes on one singular page?

e.g. https://inplayempire.com/best-uk-bookmakers/top-uk-betting-sites/

Best
Charlie

**Comment by kamalkhan** [comment]
By default, the star ratings is applied for the current post/page or custom post being viewed.

In your case, you want to distinguish star ratings in the same post/page without sticking it to the current post id. To do that, you have to manually use the shortcode and set the id of the custom post.

Example shortcode use case:

```html
Product Foo [kkstarratings id="590"]
Product Bar [kkstarratings id="591"]
Product Baz [kkstarratings id="592"]
```

**Comment by elieli88** [comment]
If you use id's where do you explain the id? In css? 
And how ?
