### ISSUE TITLE
Help with ratings not in google

### ISSUE THREAD

**Issue by tristadeleon** [kamalkhan/kk-star-ratings#42]
Is there an update to the version I have, because it doesn't seem to be working like it used to. Which is really sad. Version 2.6  - been using plugin for years and seems like it just stopped really working .. also, was wondering if you could help me get it out of the area it shows up in on my product page .. drives me crazy that it's way down there instead of by the product. Example: https://www.scentswarmers.com/buy/scentsy/zen-rock-2

**Comment by thu2018** [comment]
Learn about Structured Data. It looks like google updated the algorithm
