### ISSUE TITLE
Open Wordpress - Support Tickets 

### ISSUE THREAD

**Issue by muellmanns** [kamalkhan/kk-star-ratings#44]
Das neue Datenschutzgesetz:
https://wordpress.org/support/topic/kk-star-rating-dsgvo-compliant/

Fastest Cache
https://wordpress.org/support/topic/problem-with-wp-fastest-cache-and-manual-installation-in-the-theme/

**Comment by kamalkhan** [comment]
Thanks for this info. So replacing the digits after the last dot with 0 or X will be compliant?

**Comment by muellmanns** [comment]
Google doesn't do anonymization any differently https://en.ryte.com/wiki/Anonymizing_Google_Analytics . 

Do you have any ideas about caching? 
`<?php if(function_exists("kk_star_ratings")) : echo kk_star_ratings($pid); endif; ?>`

**Comment by muellmanns** [comment]
Hi, 

you are of the opinion to revise the topic "data protection" in time.
