### ISSUE TITLE
Voting not working on mobile

### ISSUE THREAD

**Issue by notloc27** [kamalkhan/kk-star-ratings#5]
The voting is not working on mobile devices, nor are the starts populating. Do you have a solution already built into the plugin?

Half of my visitors are on mobile devices so it would be great if I could have mobile users vote.

**Comment by SophieDurial** [comment]
On mobile you can see the stars but no vote available... 
egg : [http://blog.laplateformedelarenovation.fr/google-spaces/](url)
All users have the same issue ?

**Comment by kamalkhan** [comment]
Please read Issue #18

**Comment by Nio-av** [comment]
Is there anything new?
You closed Ticket #34 3 days ago. Is that a "won't fix' or a duplicate?

**Comment by kamalkhan** [comment]
I think this is fixed in #67
