### ISSUE TITLE
Can not save setting

### ISSUE THREAD

**Issue by haynhat** [kamalkhan/kk-star-ratings#61]
Hello developer,

I have problem with saving change of setting after using for a time. At the beginning I can save and reset the rating normally. The problem may related when I switch to unique voting from non unique voting and for the cache plugin, I still can do multi votes from 1 IP, that might cause a wrong statistic and conflict

**Comment by Budget101** [comment]
same. Cannot save the settings, they show as save, never update and instantly revert. Aggravating at best.
