### ISSUE TITLE
Error "Field ratingValue may not be empty"

### ISSUE THREAD

**Issue by techmarkm** [kamalkhan/kk-star-ratings#62]
I'm currently using version 2.6.1 with Wordpress 5.0.2. However when testing my page with Google Structured Data Testing Tool (https://search.google.com/structured-data/testing-tool), I receive an error "Field ratingValue may not be empty".

In more details, AggregateRating only has ratingCount, bestRating, and worstRating, but no ratingValue. Is the plugging not working properly or I'm missing something?

**Comment by kamalkhan** [comment]
Are you using [avg] in the legend? because it is required for grs.

**Comment by techmarkm** [comment]
Thanks for your reply! I didn't see any option regarding [avg] in the legend.

All the fields shown from the plugin are in AggregateRating: https://imgur.com/a/g2JjAKb

My URL is: https://newtechshop.vn/samsung-galaxy-watch-46mm

Could you give some help on the missing ratingValue field?

**Comment by kamalkhan** [comment]
It seems like you are only showing the count in your ratings output. Google rich snippets for ratings requires the ratingValue so you will have to use [avg] when displaying the results.

To use the [avg], head over to the plugins settings page on the general tab and look for the legend field.

**Comment by techmarkm** [comment]
Thank you for your help - I've added the [avg] field to the legend. Is there anyway I can change the itemReviewed type from CreativeWork to Product instead? The rating sadly still doesn't show up on Google Search Result Page.
