### ISSUE TITLE
Include Option for customised suffix.

### ISSUE THREAD

**Issue by Nio-av** [kamalkhan/kk-star-ratings#69]
See pull Request #68 

Problem: plural of votes is not always a word ending with 's'.

e.g. in english:
1 vote, 15 votes

e.g. in german:
1 Bewertung, 15 Bertungen

so, the current plugin is not compatable with all languages.

--->
@kamalkhan Please include an option / accept my pull request.

**Comment by kamalkhan** [comment]
Merged #68.
