### ISSUE TITLE
Access Control and extract count and rating per post

### ISSUE THREAD

**Issue by micheelengronne** [kamalkhan/kk-star-ratings#7]
Hello,

I would like to use your plugin in a wordpress website but there are 2 things I didn't manage to clarify.

Is there a way to add extra access controls to the rating ? For instance, everybody can see the rating but only authenticated people can rate.

Is there a function to retrieve the count and rating of a post ? I would like to implement an aggregateRating in a custom schemaorg.

Thanks.

**Comment by kamalkhan** [comment]
Please read Issue #18
