### ISSUE TITLE
kk Star Ratings Not Visible

### ISSUE THREAD

**Issue by Kaziaminulislamrahat** [kamalkhan/kk-star-ratings#70]
I have used kk Star Ratings plugins after last update it's not visible. check the[ image here]( http://prntscr.com/n332rg). Also you can visit my website one [URL](http://kaziaminulislam.com/%E0%A6%97%E0%A7%87%E0%A6%B8%E0%A7%8D%E0%A6%9F-%E0%A6%AA%E0%A7%8B%E0%A6%B8%E0%A7%8D%E0%A6%9F%E0%A7%87%E0%A6%B0-%E0%A6%86%E0%A6%A6%E0%A7%8D%E0%A6%AF%E0%A7%8B%E0%A6%AA%E0%A6%BE%E0%A6%A8%E0%A7%8D%E0%A6%A4/). would you please tell me how can fix the issue.

**Comment by kamalkhan** [comment]
Your images are not correctly set.

Upload the stars in the plugin settings again.

**Comment by Kaziaminulislamrahat** [comment]
Thanks for your reply. It's looks great now.
