### ISSUE TITLE
How to enable kk star rating on bbPress topics

### ISSUE THREAD

**Issue by shibaa987** [kamalkhan/kk-star-ratings#74]
I am running bbPress forum on my website.
kk star rating does not appear on any bbpress forum topics.

Can anyone please let me know how can I enable kk star ratings on bbpress forum topics?

Here is a sample link:
https://www.cyanogenmods.org/forums/topic/unlock-bootloader-android-phone-using-fastboot/

**Comment by kamalkhan** [comment]
Although bbpress is not supported, you may try using the following php code snippet in your bbpress topic theme/template file:

```php
if (function_exists('kk_star_ratings')) {
    echo kk_star_ratings($id);
}
```

Where `$id` should be the id of the post/topic.

**Comment by shibaa987** [comment]
You are awesome @kamalkhan 
I really appreciate your lighting fast response. :)

I have added the following code in template-parts/single-page.php file
```
if (function_exists('kk_star_ratings')) {
    echo kk_star_ratings($post->ID);
}
```

This might be helpful for someone looking to add kk star ratings on bbPress.
