### ISSUE TITLE
Javascript To Footer How To?

### ISSUE THREAD

**Issue by tosunkaya** [kamalkhan/kk-star-ratings#8]
I want to move kk star ratings's javascript to footer:

<script type="text/javascript">var bhittani_plugin_kksr_js = {"nonce":"2a29e98257","grs":true,"ajaxurl":"https:\/\/tosunkaya.com\/wp-admin\/admin-ajax.php","func":"kksr_ajax","msg":"Makaleye Oy Verin","fuelspeed":400,"thankyou":"Te\u015fekk\u00fcrler :)","error_msg":"Bir hata olu\u015ftu :(","tooltip":"0","tooltips":[{"tip":"Be\u011fenmedim","color":"#FF2600"},{"tip":"\u0130yi De\u011fil","color":"#FFA200"},{"tip":"Eh i\u015fte","color":"#EEFF00"},{"tip":"\u0130yi","color":"#AEFF00"},{"tip":"S\u00fcper","color":"#00F508"}]};</script>

how to do this? It is automatically adding. Please help me.

my website: https://tosunkaya.com

I tried remove this code and add to footer, cache didnt work with.

<script type="text/javascript" defer src="/wp-content/plugins/kk-star-ratings/js.min.js"></script> to footer and remove code from plugin index.php

add_action('wp_enqueue_scripts', array($kkStarRatings_obj, 'js'));

This didnt work. Please help.

**Comment by kamalkhan** [comment]
Please read Issue #18
