### ISSUE TITLE
Stars appear everywhere

### ISSUE THREAD

**Issue by fastbook** [kamalkhan/kk-star-ratings#80]
Stars started appearing everywhere

I have more than one wysiwyg textboxes in aevery post.
After the last upgrade of the plugin ..star rating appear in every textbox and its very frustrating for visitors.!! I had to reupload the previus version of the plugin that works fine.
Please see this issue because your rating plugin is probably the best for wordpress and star really appear in google search!

Thanks in advance.

**Comment by kamalkhan** [comment]
https://wordpress.org/support/topic/use-2-6-4-instead-of-v3/
