### ISSUE TITLE
Bug Exclude Category

### ISSUE THREAD

**Issue by stefa98** [kamalkhan/kk-star-ratings#89]
Hello!

congratulations for the plugin, just what I was looking for! But I discovered a problem:

If I try to exclude a sub-category from the kk stars settings section, there are no sub-categories among the categories.

can you solve? thanks

**Comment by QasimYad** [comment]
> Hello!
> 
> congratulations for the plugin, just what I was looking for! But I discovered a problem:
> 
> If I try to exclude a sub-category from the kk stars settings section, there are no sub-categories among the categories.
> 
> can you solve? thanks

Hi Stefa98!

Some time categories or subcategories does not showup if we have no posts categories. If this this with your case, kindly add a post in category in post. I hope this will resolve the issue.

**Comment by QasimYad** [comment]
> Hello!
> 
> congratulations for the plugin, just what I was looking for! But I discovered a problem:
> 
> If I try to exclude a sub-category from the kk stars settings section, there are no sub-categories among the categories.
> 
> can you solve? thanks

Yeah You are right, it is bug. @stefa98

**Comment by stefa98** [comment]
> > Hello!
> > congratulations for the plugin, just what I was looking for! But I discovered a problem:
> > If I try to exclude a sub-category from the kk stars settings section, there are no sub-categories among the categories.
> > can you solve? thanks
> 
> Yeah You are right, it is bug. @stefa98

I hope you will solve it quickly :) @QasimYad

**Comment by kamalkhan** [comment]
I did not understand the issue. The exclude categories section only shows the parent categories. Child categories are not shown on purpose.

**Comment by stefa98** [comment]
why are they not displayed on purpose?

**Comment by stefa98** [comment]
??

**Comment by QasimYad** [comment]
> why are they not displayed on purpose?

Hello @stefa98 !
I hope you are doing well. I was also wondering why sub-categories are not displaying and @kamalkhan  has 2nd time mentioned that he has some concern to do this. So, we should get this feature added by editing the code. I am trying too. I will updated here when i will succeed. Thanks
