### ISSUE TITLE
Feature Request: Ability to check for a custom post type so schema.org spec could be changed.

### ISSUE THREAD

**Issue by monecchi** [kamalkhan/kk-star-ratings#9]
I'm just giving the plugin a try. It is indeed very straight forward and easy to set up, thanks!

Anyway, I believe users would benefit a lot more if they could fit the ratings to the right schema.org spec. The plugin could offer an option to choose custom post types such as product, recipe, book, movies etc, and then output the proper schema.org spec for the ratings. I believe this way the content being served by WordPress would be more coherent for generating the Google Rich Snippets. Those custom post types are very generic and a lot of sites are focused on those kind of content nowadays. 

Being able to output the right schema.org spec would be great! Another extra option could allow the user to define his/her own schema.org spec.

I use WordPress for a food restaurant website to display a custom food menu post type, I also use WooCommerce Plugin. This custom post type is already set up so that Google can display rich snippets, but what I'm missing is the **schema.org** **[AggregateRating](https://schema.org/AggregateRating)** spec.

I'll do my best to build this options myself as I'm not a dev, and if they fit well perhaps I could make a PR.

Thanks in advance.

**Comment by kamalkhan** [comment]
Please read Issue #18
