### ISSUE TITLE
Shortcode display for general users

### ISSUE THREAD

**Issue by sakthiwebdev** [kamalkhan/kk-star-ratings#94]
I know, you have given a shortcode to use on pages/post. but you haven't mentioned the shortcode anywhere on the plugin front-end. 

I saw the shortcode on plugin code and using that shortcode to display on my elementor single post template.

On next update, show it on the plugin settings. so that people can make use of it.

**Comment by timomedia** [comment]
Hello!
Please tell me the shortcode!
Thank you very much!

**Comment by kamalkhan** [comment]
```php
[kkstarratings]
```

**Comment by timomedia** [comment]
Thanks!

Vào Th 7, 25 thg 4, 2020 vào lúc 03:13 Kamal Khan <
notifications@github.com> đã viết:
