### ISSUE TITLE
Invalid item detected on Google Search Console

### ISSUE THREAD

**Issue by Cec343** [kamalkhan/kk-star-ratings#97]
Hi,

When inspecting a page on Search Console (the plugin is activated and the page has some ratings), I get the following issue:

**1 invalid item detected
Invalid items are not eligible for Google Search's rich results.**

Unnamed item
4 errors
- Missing field "ratingValue"
- Invalid object type for field "itemReviewed"
- Either "ratingCount" or "reviewCount" should be specified
- Missing reviewed item name

Any different settings could help fix this?

Thank you

**Comment by orenatan** [comment]
Follow
