### ISSUE TITLE
Can't Change Color of Stars

### ISSUE THREAD

**Issue by mstrong33** [kamalkhan/kk-star-ratings#98]
I just installed kk star plugin and it will not allow me to change the color of the stars. The description says that this is a feature but it's not working. It will only create yellow stars on a desktop and orange starts on a mobile device. Is anyone else having this issue? I would like to keep this plugin, but it's not working! Please fix this so I can change the color to match the color themes on my website. Thank You

* Version used: PHP 7
* Operating system and version 
* Link to your project: www.thegreenyogi.com
* ...
* ...

**Comment by kamalkhan** [comment]
This feature was discontinued since v3. You can do this manually by editing the svg files in `public/svg`.

For example, the `active.svg` is orangish in color. To change the color, simply open the file in an editor and change the `fill` and `stroke` color values.

**Comment by mstrong33** [comment]
Thank you so much Kamal!! I SO appreciate you and your fast response. This will save me so much time converting to another star rating. 

I hope you are doing well during this time. Wishing you health!

With Gratitude,

Mary

The Green Yogi Online
www.thegreenyogi.com
c: 310.980.2021
e: mary@thegreenyogi.com

**Comment by Yerrun** [comment]
Will these changes get lost with a new plugin update?

**Comment by Yerrun** [comment]
This svg editor was quite simple and handy: [](https://boxy-svg.com/app)

**Comment by Yerrun** [comment]
> Will these changes get lost with a new plugin update?

Whooooops sorry. There aren't any plugin updates.
